Update patches 4.5 patches for 4.5.2, add --disable-druntime-gc configure flag for disable building the GC into libgdruntime, instead using the gcstubs.

diff --git a/d/config-lang.in b/d/config-lang.in
--- a/d/config-lang.in
+++ b/d/config-lang.in
@@ -21,7 +21,19 @@ language="d"
 compilers="cc1d\$(exeext)"
 stagestuff="gdc\$(exeext) gdc-cross\$(exeext) cc1d\$(exeext)"
 
-d_gcc_version=$(echo ${gcc_version} | sed -e 's/\([0-9]*\)\.\([0-9]*\).*/\1\2/')
+# This file can be called from one of two places,
+# so ensure we account for both.
+d_gcc_version=
+if [ -e $srcdir/gcc/BASE-VER ]; then
+  d_gcc_version=$(cat $srcdir/gcc/BASE-VER)
+elif [ -e $srcdir/BASE-VER ]; then
+  d_gcc_version=$(cat $srcdir/BASE-VER)
+else
+  echo "Sorry, cannot find BASE-VER"
+  exit 1
+fi
+
+d_gcc_version=$(echo $d_gcc_version | sed -e 's/\([0-9]*\)\.\([0-9]*\).*/\1\2/')
 if [ ${d_gcc_version} -ge 45 ]; then
   gtfiles="\$(srcdir)/d/d-lang-45.h \$(srcdir)/d/d-builtins.c"
 else
