Re-add GNU_Need_execvpe for D2 libphobos

diff --git a/d/phobos2/configure b/d/phobos2/configure
--- a/d/phobos2/configure
+++ b/d/phobos2/configure
@@ -5735,9 +5735,108 @@ fi
 # AC_SUBST(DCFG_EXPM1)
 # also erf, erfc
 
-# use version(Unix) instead.
-#AC_CHECK_FUNC(execvpe,DCFG_EXECVPE="",DCFG_EXECVPE="GNU_Need_execvpe")
-#AC_SUBST(DCFG_EXECVPE)
+echo "$as_me:$LINENO: checking for execvpe" >&5
+echo $ECHO_N "checking for execvpe... $ECHO_C" >&6
+if test "${ac_cv_func_execvpe+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test x$gcc_no_link = xyes; then
+  { { echo "$as_me:$LINENO: error: Link tests are not allowed after GCC_NO_EXECUTABLES." >&5
+echo "$as_me: error: Link tests are not allowed after GCC_NO_EXECUTABLES." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define execvpe to an innocuous variant, in case <limits.h> declares execvpe.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define execvpe innocuous_execvpe
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char execvpe (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef execvpe
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char execvpe ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_execvpe) || defined (__stub___execvpe)
+choke me
+#else
+char (*f) () = execvpe;
+#endif
+#ifdef __cplusplus
+}
+#endif
+
+int
+main ()
+{
+return f != execvpe;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_func_execvpe=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_func_execvpe=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_func_execvpe" >&5
+echo "${ECHO_T}$ac_cv_func_execvpe" >&6
+if test $ac_cv_func_execvpe = yes; then
+  DCFG_EXECVPE=""
+else
+  DCFG_EXECVPE="GNU_Need_execvpe"
+fi
+
+
 
 echo "$as_me:$LINENO: checking for spawnvp" >&5
 echo $ECHO_N "checking for spawnvp... $ECHO_C" >&6
